spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
  datasource:
    url: jdbc:postgresql://localhost:5432/FIDO2_SERVER
    username: postgres
    password: postgres
  liquibase:
    drop-first: false

app:
  metadata:
    mds3-endpoints:
      # https://api.localhost.ssl:10011/webauthn
      - https://mds3.fido.tools/execute/22f80bc9198dcb014463e386bc720293c6ec7b40158d1f835c131cee54607096
      - https://mds3.fido.tools/execute/565c0175b71e18cbeb3b97885ab2f0bd48008e75feb008c27e0f58fc24745aeb
      - https://mds3.fido.tools/execute/a33e73edef628df9d885e0df29f418ead195af22979ffae18fe4e5a6a512c0cd
      - https://mds3.fido.tools/execute/c6b48384afb124e8089c67d184380b67f492421506f83a891bec83a9da5ba454
      - https://mds3.fido.tools/execute/b8b5a4127ad31b18f32a373913ee3f7b5dcd59252be5022a60ba7a5c1339c45c

server:
  port: 10011
  ssl:
    enabled: true
    key-store: classpath:ssl/_.localhost.ssl_2023.p12
    key-store-password: 123
    key-store-type: pkcs12
    key-password: 123
