package com.stid.project.fido2server.app.domain.constant;

public enum EventName {
    RELYING_PARTY_GET_ACCESS_TOKEN,
    RELYING_PARTY_UPDATE_INFO,
    RELYING_PARTY_CREATE_USER,
    RELYING_PARTY_DELETE_USER,
    RELYING_PARTY_UPDATE_AUTHENTICATOR,
    RELYING_PARTY_DELETE_AUTHENTICATOR,
    RELYING_PARTY_ATTESTATION_OPTIONS,
    RELYING_PARTY_ATTESTATION_RESULT,
    RELYING_PARTY_ASSERTION_OPTIONS,
    RELYING_PARTY_ASSERTION_RESULT,
    ;
}
